language: generic

dist: bionic

## Uncomment the following lines if you require extra dependencies
before_install:
# - sudo apt-get install ghostscript # If you use latex > dvips > ps2pdf
# - sudo apt-get install python-pygments # If you use the minted package
  # If you use custom fonts:
 - mkdir $HOME/.fonts
# - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
 - fc-cache -f -v

install:
  - source ./texlive/texlive_install.sh
  - curl -OL http://www.tug.org/fonts/getnonfreefonts/install-getnonfreefonts && texlua ./install-getnonfreefonts && rm -f install-getnonfreefonts && getnonfreefonts --sys garamondx
#  - updmap-sys

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

# Change working directory so including files will work
#before_script:
script:
  # Texliveonfly will download packages automatically
  - texliveonfly --engine=pdflatex --arguments="-synctex=1 -interaction=nonstopmode" thesismain.tex
  # You can use latexmk to automatically handle bibtex and references (recommended)
#  - latexmk -pdf thesismain.tex

  # But you could use any other compiler as well instead of latexmk. Example:
  - pdflatex -synctex=1 -interaction=nonstopmode -undump=pdflatex thesismain.tex
  - biber thesismain
  - makeglossaries thesismain.tex
  - pdflatex -synctex=1 -interaction=nonstopmode -undump=pdflatex thesismain.tex
  - pdflatex -synctex=1 -interaction=nonstopmode -undump=pdflatex thesismain.tex # Compile twice to fix references

  # You can also pass arguments to texliveonfly:
#  - texliveonfly --arguments='-shell-escape' thesismain.tex

## Uncomment the following lines to see the packages installed in travis
#after_script:
#  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
#  - tlmgr list --only-installed | grep -oP 'i \K.+?(?=:)'
