language: generic

dist: bionic

## Uncomment the following lines if you require extra dependencies
before_install:
 - mkdir $HOME/.fonts
 - fc-cache -f -v

install:
  - source ./texlive/texlive_install.sh
  - curl -OL http://www.tug.org/fonts/getnonfreefonts/install-getnonfreefonts && texlua ./install-getnonfreefonts && rm -f install-getnonfreefonts && getnonfreefonts --sys garamondx
#  - updmap-sys

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  # Texliveonfly will download packages automatically
  - echo -e "\033[1mFirst run of compiling to install packages\033[0m"
  - texliveonfly --arguments="-synctex=1 -interaction=nonstopmode" thesismain.tex

  # But you could use any other compiler as well instead of latexmk. Example:
  - echo -e "\033[1mFirst run of pdflatex\033[0m"
  - pdflatex -synctex=1 -interaction=nonstopmode thesismain.tex
  - echo -e "\033[1mRunning biber\033[0m"
  - biber thesismain
  - echo -e "\033[1mMaking glossary\033[0m"
  - makeglossaries thesismain
  - echo -e "\033[1mSecond run of pdflatex\033[0m"
  - pdflatex -synctex=1 -interaction=nonstopmode thesismain.tex
  - echo -e "\033[1mFinal run of pdflatex\033[0m"
  - pdflatex -synctex=1 -interaction=nonstopmode thesismain.tex  # Compile twice to fix references

# COPY thesismain.tex -> thesismain_draft.tex and run pdflatex commands with -draftmode option as well to create draft version of pdf. Also try to include a word counter script